language: python
python: 2.7

cache:
    pip: true
    directories: .venv

before_install:
    - virtualenv .venv
    - source .venv/bin/activate
    - pip install --upgrade pip

install:
    - pip install -e .[test]

script:
    - nose2 sllurp
